# Generated by Django 4.0.1 on 2022-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
