# Generated by Django 4.0.1 on 2022-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220218_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер телефона'),
        ),
    ]
