# Generated by Django 3.2.6 on 2022-02-11 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 14, 37, 29, 151941, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='productColor gallery', verbose_name='Фото продукта')),
                ('productColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_products', to='app.productcolor', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
