# Generated by Django 3.2.6 on 2022-02-14 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220211_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=256, null=True, verbose_name='Hex'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 14, 2, 58, 51479, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
