# Generated by Django 3.2.6 on 2022-02-14 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220214_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 14, 7, 57, 281403, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_products', to='app.product', verbose_name='Продукт'),
        ),
    ]
