# Generated by Django 3.2.6 on 2022-02-14 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220214_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 14, 14, 46, 990354, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
