# Generated by Django 3.2.6 on 2022-02-16 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 15, 46, 30, 76983, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='ProductColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_productsColors', to='app.memory', verbose_name='Память')),
                ('productColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_productsColors', to='app.productcolor', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Цена продукта',
                'verbose_name_plural': 'Цены продукта',
            },
        ),
    ]
