# Generated by Django 3.2.6 on 2022-02-18 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220216_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 13, 40, 2, 319574, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
