# Generated by Django 3.2.6 on 2022-02-21 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220218_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 14, 5, 43, 811114, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
