# Generated by Django 3.2.6 on 2022-03-04 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220225_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order Product', 'verbose_name_plural': 'Order Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 13, 39, 22, 548913, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кол-во товара в наличии')),
                ('storage_type', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('productColorSize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productcolorsize', verbose_name='Продукт')),
            ],
        ),
    ]
