# Generated by Django 3.2.6 on 2022-03-26 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220326_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 13, 53, 21, 711128, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productcolorsize',
            name='memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_productsColors', to='app.memory', verbose_name='Память'),
        ),
    ]
