# Generated by Django 4.0.1 on 2022-04-19 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_product_created_at_alter_productgallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='productcolorsize',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 13, 2, 54, 2253, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
