# Generated by Django 4.0.1 on 2022-04-25 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_product_created_at_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 9, 37, 22, 444249, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
