# Generated by Django 4.0.1 on 2022-04-27 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 8, 15, 53, 202867, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
