# Generated by Django 4.0.1 on 2022-06-25 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 6, 28, 49, 257903, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
